### ISSUE TITLE
Auth0 pagination is not handling more than 1 page of results

### ISSUE THREAD

**Issue by vasilisgav** [airbytehq/airbyte#29358]
### Connector Name

source-auth0

### Connector Version

0.3.0

### What step the error happened?

During the sync

### Revelant information

The paginator in source-auth0 expects in body the length property
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-auth0/source_auth0/source.py#L47

but the body has no such field.
so it always lands here https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-auth0/source_auth0/source.py#L65-L71

as result only 50 results at a time are retrieved.

To produce this, pick a source that with a single request retrieves more than 50 results, its easier with streams such as: clients, users, organizations

### Contribute

- [X] Yes, I want to contribute

**Comment by vasilisgav** [comment]
@sajarin can you please reopen this? this is not closed

**Comment by sajarin** [comment]
@vasilisgav can you confirm this isn't working on version 0.4.1 of the connector?

**Comment by vasilisgav** [comment]
The issue is even bigger, it cannot even be tested, the connection is now broken because of this https://github.com/airbytehq/airbyte/issues/29789

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
