### ISSUE TITLE
[source-Auth0] Connection settings with OAuth2 Confidential Application 

### ISSUE THREAD

**Issue by vasilisgav** [airbytehq/airbyte#31858]
### Connector Name

Auth0

### Connector Version

0.4.1 0 or later

### What step the error happened?

Configuring a new connector

### Relevant information

As described [here](https://github.com/airbytehq/airbyte/issues/29789#issuecomment-1738493981)
unable to connect to connector

### Relevant log output

```shell
2023-09-28 05:29:38 INFO i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-09-28 05:29:38 INFO i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-09-28 05:29:38 INFO i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-09-28 05:29:38 INFO i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-09-28 05:29:38 INFO i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-auth0:0.4.1 exists...
2023-09-28 05:29:38 INFO i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-auth0:0.4.1 was found locally.
2023-09-28 05:29:38 INFO i.a.w.p.DockerProcessFactory(create):130 - Creating docker container = source-auth0-check-7eb9ccde-99ee-421c-ac2b-05ff680efe82-0-ucntt with resources io.airbyte.config.ResourceRequirements@5caf99ff[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=] and allowedHosts null
2023-09-28 05:29:38 INFO i.a.w.p.DockerProcessFactory(create):175 - Preparing command: docker run --rm --init -i -w /data/7eb9ccde-99ee-421c-ac2b-05ff680efe82/0 --log-driver none --name source-auth0-check-7eb9ccde-99ee-421c-ac2b-05ff680efe82-0-ucntt --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e STRICT_COMPARISON_NORMALIZATION_WORKSPACES= -e WORKER_CONNECTOR_IMAGE=airbyte/source-auth0:0.4.1 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e STRICT_COMPARISON_NORMALIZATION_TAG=strict_comparison2 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.42.0 -e WORKER_JOB_ID=7eb9ccde-99ee-421c-ac2b-05ff680efe82 airbyte/source-auth0:0.4.1 check --config source_config.json
2023-09-28 05:29:38 INFO i.a.w.i.VersionedAirbyteStreamFactory(create):107 - Reading messages from protocol version 0.2.0
2023-09-28 05:29:39 ERROR i.a.w.i.DefaultAirbyteStreamFactory(internalLog):164 - Encountered an error trying to connect to stream clients. Error: 
 Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 235, in _get_request_options
    auth_options_method(),
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 39, in get_auth_header
    return {"Authorization": f"Bearer {self.get_access_token()}"}
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 44, in get_access_token
    token, expires_in = self.refresh_access_token()
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/auth/oauth.py", line 118, in refresh_access_token
    response_json = self._get_refresh_access_token_response()
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 93, in _get_refresh_access_token_response
    if e.response.status_code == 429 or e.response.status_code >= 500:
AttributeError: 'NoneType' object has no attribute 'status_code'
2023-09-28 05:29:39 ERROR i.a.w.i.DefaultAirbyteStreamFactory(internalLog):164 - Check failed
2023-09-28 05:29:40 INFO i.a.w.g.DefaultCheckConnectionWorker(run):120 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@626b406b[status=failed,message="Unable to connect to stream clients - 'NoneType' object has no attribute 'status_code'"]
2023-09-28 05:29:40 INFO i.a.w.t.TemporalAttemptExecution(get):169 - Stopping cancellation check scheduling...
2023-09-28 05:29:40 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-09-28 05:29:40 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-09-28 05:29:40 INFO i.a.c.i.LineGobbler(voidCall):149 - 
```
```


### Contribute

- [ ] Yes, I want to contribute

**Comment by sumeetgajjar** [comment]
We faced the same when upgrading to 0.5.1. 
The logs indicate `Errno -2] Name does not resolve`.

And if you go further above in the logs, the exception shall contain an HTTPSConnectionPool object with a hostname like `*****.auth0.comoauth`

```sh
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='*****.auth0.comoauth', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ff100eea250>: Failed to resolve 'revefi.us.auth0.comoauth' ([Errno -2] Name or service not known)"))
```

-----

We were able to by-pass the above error after adding a `/` at the end of `base_url` in the `airbyte auth0 source configuration`

However, once we resolved that, the following exception surfaced
```sh
requests.exceptions.HTTPError: 400 Client Error: Bad Request for URL:
```

-----

### Auth0 Logs

Investigating further in the Auth0 logs shows the following issue
```json
"description": "Missing required parameter: refresh_token",
```

We traced the property to the `auth0 manifest.yaml` file: https://github.com/airbytehq/airbyte/blob/d975ead34a5f0623af9887798c1a4df8c807a926/airbyte-integrations/connectors/source-auth0/source_auth0/manifest.yaml#L15

The following PR #29804 added it and shall require further investigation on why that field is kept empty.

----


Hi @sajarin and @archangelic - given you were the author and reviewer of the above PR respectively, 
can you please shed some light on why that field was kept empty?

As per the following Airbyte doc: https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/authentication#oauth, the `refresh_token` is a required field.

**Comment by francois-beauchemin** [comment]
@sumeetgajjar  where you able to make auth0 connector working ?

I'm facing the same issue where auth0 logs talk about required  refersh_token 

its strange cause in client_credential flow  that should probably be used by this connector, refresh token is not supporte if im  not mistaken...

**Comment by francois-beauchemin** [comment]
OAuthAuthenticator  had support added for client_crential flow it seems in https://github.com/airbytehq/airbyte/pull/26031


The source-auth0 connector should probably specify this in the grant type in the manifest ?

**Comment by sumeetgajjar** [comment]
> @sumeetgajjar where you able to make auth0 connector working ?

Hi @francois-beauchemin - I could not get the `0.5.1` version working in our OSS deployment, so decided to downgrade it back to `0.2.0` which worked out of the box. Having said that, I did not try the latest version: `0.5.7`.


> its strange cause in client_credential flow that should probably be used by this connector, refresh token is not supporte if im not mistaken...

I suppose for the client_credential flow to work the refresh_token field in the auth0 [manifest.yaml](https://github.com/airbytehq/airbyte/blob/2c2d841f5b93c8aaadf37163d88c6d2c2e858257/airbyte-integrations/connectors/source-auth0/source_auth0/manifest.yaml#L15) needs to be set to `"{{ config['credentials']['refresh_token'] }}"` or something similar

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by kcarrillorhoads** [comment]
This problem is still occurring on version 0.6.2 for the auth0 source (now defined via terraform) where you need to add an additional '/' but then you get the error:
400 Client Error: Bad Request for url: https://om1inc.us.auth0.com/oauth/token'

**Comment by kcarrillorhoads** [comment]
And API access tokens have a max life of 30 days.

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for 180 days, suggesting that it's not as critical as others. It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by max-mathieu** [comment]
This is still unresolved -- similar issues are above
