### ISSUE TITLE
Destination Snowflake: Upgrading from snowflake 1.1.0 to 1.2.0 causes Chargebee to snowflake sync to fail.

### ISSUE THREAD

**Issue by ShayePearson** [airbytehq/airbyte#28225]
### Connector Name

destination-snowflake

### Connector Version

1.2.0

### What step the error happened?

During the sync

### Revelant information

<img width="1180" alt="image" src="https://github.com/airbytehq/airbyte/assets/10830210/174f326d-afcd-4ba4-8399-c12d0fd8269e">

After upgrading snowflake destination to 1.2.0 the Chargebee sync started to fail. Downgrading back to 1.1.0 resolved the issue. Other source's seemed to work after the upgrade. Cargebee was the only issue. 

Running Airbyte version 0.50.6
Chargebee source: 0.2.3 

### Relevant log output

```shell
2023-07-11 03:04:59 destination > ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 37 unexpected 'ORDER'.
syntax error line 1 at position 36 unexpected '.'.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127) ~[snowflake-jdbc.jar:3.13.19]
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67) ~[snowflake-jdbc.jar:3.13.19]
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:451) ~[snowflake-jdbc.jar:3.13.19]
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:354) ~[snowflake-jdbc.jar:3.13.19]
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:488) ~[snowflake-jdbc.jar:3.13.19]
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:198) ~[snowflake-jdbc.jar:3.13.19]
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135) ~[snowflake-jdbc.jar:3.13.19]
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:768) ~[snowflake-jdbc.jar:3.13.19]
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:678) ~[snowflake-jdbc.jar:3.13.19]
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287) ~[snowflake-jdbc.jar:3.13.19]
	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342) ~[snowflake-jdbc.jar:3.13.19]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-5.0.1.jar:?]
	at io.airbyte.db.jdbc.JdbcDatabase.lambda$execute$0(JdbcDatabase.java:49) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
	at io.airbyte.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:46) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
	at io.airbyte.db.jdbc.JdbcDatabase.execute(JdbcDatabase.java:49) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
	at io.airbyte.integrations.destination.snowflake.SnowflakeInternalStagingSqlOperations.createStageIfNotExists(SnowflakeInternalStagingSqlOperations.java:140) ~[io.airbyte.airbyte-integrations.connectors-destination-snowflake-24.0.2.jar:?]
	at io.airbyte.integrations.destination.staging.GeneralStagingFunctions.lambda$onStartFunction$0(GeneralStagingFunctions.java:40) ~[io.airbyte.airbyte-integrations.bases-bases-destination-jdbc-24.0.2.jar:?]
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-24.0.2.jar:?]
	at io.airbyte.integrations.destination_async.AsyncStreamConsumer.start(AsyncStreamConsumer.java:96) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:221) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:212) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$0(IntegrationRunner.java:151) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:270) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:155) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.base.adaptive.AdaptiveDestinationRunner$Runner.run(AdaptiveDestinationRunner.java:87) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
	at io.airbyte.integrations.destination.snowflake.SnowflakeDestinationRunner.main(SnowflakeDestinationRunner.java:18) ~[io.airbyte.airbyte-integrations.connectors-destination-snowflake-24.0.2.jar:?]
	Suppressed: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 31 unexpected 'ORDER'.
		at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127) ~[snowflake-jdbc.jar:3.13.19]
		at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67) ~[snowflake-jdbc.jar:3.13.19]
		at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:451) ~[snowflake-jdbc.jar:3.13.19]
		at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:354) ~[snowflake-jdbc.jar:3.13.19]
		at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:488) ~[snowflake-jdbc.jar:3.13.19]
		at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:198) ~[snowflake-jdbc.jar:3.13.19]
		at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135) ~[snowflake-jdbc.jar:3.13.19]
		at net.snowflake.client.core.SFStatement.execute(SFStatement.java:768) ~[snowflake-jdbc.jar:3.13.19]
		at net.snowflake.client.core.SFStatement.execute(SFStatement.java:678) ~[snowflake-jdbc.jar:3.13.19]
		at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287) ~[snowflake-jdbc.jar:3.13.19]
		at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342) ~[snowflake-jdbc.jar:3.13.19]
		at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-5.0.1.jar:?]
		at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-5.0.1.jar:?]
		at io.airbyte.db.jdbc.JdbcDatabase.lambda$execute$0(JdbcDatabase.java:49) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
		at io.airbyte.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:46) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
		at io.airbyte.db.jdbc.JdbcDatabase.execute(JdbcDatabase.java:49) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
		at io.airbyte.integrations.destination.snowflake.SnowflakeInternalStagingSqlOperations.dropStageIfExists(SnowflakeInternalStagingSqlOperations.java:198) ~[io.airbyte.airbyte-integrations.connectors-destination-snowflake-24.0.2.jar:?]
		at io.airbyte.integrations.destination.staging.GeneralStagingFunctions.lambda$onCloseFunction$1(GeneralStagingFunctions.java:104) ~[io.airbyte.airbyte-integrations.bases-bases-destination-jdbc-24.0.2.jar:?]
		at io.airbyte.integrations.destination.staging.StagingConsumerFactory.lambda$createAsync$0(StagingConsumerFactory.java:97) ~[io.airbyte.airbyte-integrations.bases-bases-destination-jdbc-24.0.2.jar:?]
		at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-24.0.2.jar:?]
		at io.airbyte.integrations.destination_async.AsyncStreamConsumer.close(AsyncStreamConsumer.java:161) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
		at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$0(IntegrationRunner.java:150) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
		at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:270) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
		at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:155) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
		at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
		at io.airbyte.integrations.base.adaptive.AdaptiveDestinationRunner$Runner.run(AdaptiveDestinationRunner.java:87) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
		at io.airbyte.integrations.destination.snowflake.SnowflakeDestinationRunner.main(SnowflakeDestinationRunner.java:18) ~[io.airbyte.airbyte-integrations.connectors-destination-snowflake-24.0.2.jar:?]

Stack Trace: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 37 unexpected 'ORDER'.
syntax error line 1 at position 36 unexpected '.'.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:451)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:354)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:488)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:198)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:768)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:678)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at io.airbyte.db.jdbc.JdbcDatabase.lambda$execute$0(JdbcDatabase.java:49)
	at io.airbyte.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:46)
	at io.airbyte.db.jdbc.JdbcDatabase.execute(JdbcDatabase.java:49)
	at io.airbyte.integrations.destination.snowflake.SnowflakeInternalStagingSqlOperations.createStageIfNotExists(SnowflakeInternalStagingSqlOperations.java:140)
	at io.airbyte.integrations.destination.staging.GeneralStagingFunctions.lambda$onStartFunction$0(GeneralStagingFunctions.java:40)
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
	at io.airbyte.integrations.destination_async.AsyncStreamConsumer.start(AsyncStreamConsumer.java:96)
	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:221)
	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:212)
	at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$0(IntegrationRunner.java:151)
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:270)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:155)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99)
	at io.airbyte.integrations.base.adaptive.AdaptiveDestinationRunner$Runner.run(AdaptiveDestinationRunner.java:87)
	at io.airbyte.integrations.destination.snowflake.SnowflakeDestinationRunner.main(SnowflakeDestinationRunner.java:18)
	Suppressed: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 31 unexpected 'ORDER'.
		at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
		at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
		at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:451)
		at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:354)
		at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:488)
		at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:198)
		at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135)
		at net.snowflake.client.core.SFStatement.execute(SFStatement.java:768)
		at net.snowflake.client.core.SFStatement.execute(SFStatement.java:678)
		at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287)
		at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342)
		at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
		at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
		at io.airbyte.db.jdbc.JdbcDatabase.lambda$execute$0(JdbcDatabase.java:49)
		at io.airbyte.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:46)
		at io.airbyte.db.jdbc.JdbcDatabase.execute(JdbcDatabase.java:49)
		at io.airbyte.integrations.destination.snowflake.SnowflakeInternalStagingSqlOperations.dropStageIfExists(SnowflakeInternalStagingSqlOperations.java:198)
		at io.airbyte.integrations.destination.staging.GeneralStagingFunctions.lambda$onCloseFunction$1(GeneralStagingFunctions.java:104)
		at io.airbyte.integrations.destination.staging.StagingConsumerFactory.lambda$createAsync$0(StagingConsumerFactory.java:97)
		at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
		at io.airbyte.integrations.destination_async.AsyncStreamConsumer.close(AsyncStreamConsumer.java:161)
		at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$0(IntegrationRunner.java:150)
		... 5 more

2023-07-11 03:04:59 INFO i.a.w.g.ReplicationWorkerHelper(processMessageFromDestination):219 - State in DefaultReplicationWorker from destination: io.airbyte.protocol.models.AirbyteMessage@32739d12[type=TRACE,log=<null>,spec=<null>,connectionStatus=<null>,catalog=<null>,record=<null>,state=<null>,trace=io.airbyte.protocol.models.AirbyteTraceMessage@3cb4752c[type=ERROR,emittedAt=1.689044699578E12,error=io.airbyte.protocol.models.AirbyteErrorTraceMessage@388bf662[message=Something went wrong in the connector. See the logs for more details.,internalMessage=net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 37 unexpected 'ORDER'.
syntax error line 1 at position 36 unexpected '.'.,stackTrace=net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 37 unexpected 'ORDER'.
syntax error line 1 at position 36 unexpected '.'.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:451)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:354)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:488)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:198)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:768)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:678)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at io.airbyte.db.jdbc.JdbcDatabase.lambda$execute$0(JdbcDatabase.java:49)
	at io.airbyte.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:46)
	at io.airbyte.db.jdbc.JdbcDatabase.execute(JdbcDatabase.java:49)
	at io.airbyte.integrations.destination.snowflake.SnowflakeInternalStagingSqlOperations.createStageIfNotExists(SnowflakeInternalStagingSqlOperations.java:140)
	at io.airbyte.integrations.destination.staging.GeneralStagingFunctions.lambda$onStartFunction$0(GeneralStagingFunctions.java:40)
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
	at io.airbyte.integrations.destination_async.AsyncStreamConsumer.start(AsyncStreamConsumer.java:96)
	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:221)
	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:212)
	at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$0(IntegrationRunner.java:151)
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:270)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:155)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:99)
	at io.airbyte.integrations.base.adaptive.AdaptiveDestinationRunner$Runner.run(AdaptiveDestinationRunner.java:87)
	at io.airbyte.integrations.destination.snowflake.SnowflakeDestinationRunner.main(SnowflakeDestinationRunner.java:18)
	Suppressed: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 31 unexpected 'ORDER'.
		at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
		at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
		at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:451)
		at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:354)
		at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:488)
		at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:198)
		at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135)
		at net.snowflake.client.core.SFStatement.execute(SFStatement.java:768)
		at net.snowflake.client.core.SFStatement.execute(SFStatement.java:678)
		at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287)
		at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342)
		at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
		at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
		at io.airbyte.db.jdbc.JdbcDatabase.lambda$execute$0(JdbcDatabase.java:49)
		at io.airbyte.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:46)
		at io.airbyte.db.jdbc.JdbcDatabase.execute(JdbcDatabase.java:49)
		at io.airbyte.integrations.destination.snowflake.SnowflakeInternalStagingSqlOperations.dropStageIfExists(SnowflakeInternalStagingSqlOperations.java:198)
		at io.airbyte.integrations.destination.staging.GeneralStagingFunctions.lambda$onCloseFunction$1(GeneralStagingFunctions.java:104)
		at io.airbyte.integrations.destination.staging.StagingConsumerFactory.lambda$createAsync$0(StagingConsumerFactory.java:97)
		at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
		at io.airbyte.integrations.destination_async.AsyncStreamConsumer.close(AsyncStreamConsumer.java:161)
		at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$0(IntegrationRunner.java:150)
		... 5 more
,failureType=system_error,streamDescriptor=<null>,additionalProperties={}],estimate=<null>,streamStatus=<null>,additionalProperties={}],control=<null>,additionalProperties={}]
2023-07-11 03:04:59 destination > Destination process done (exit code 1)
2023-07-11 03:04:59 destination > Skipping in-connector normalization
2023-07-11 03:06:00 ERROR i.a.w.g.DefaultReplicationWorker(replicate):211 - Sync worker failed.
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
This issue was reported when Snowflake still using normalization. Please upgrade to latest version of Destination connector to use typing-deduping method.
