### ISSUE TITLE
Destination Connector Snowflake Failing when bringing in Salesforce Order Object

### ISSUE THREAD

**Issue by cbuckle1** [airbytehq/airbyte#28357]
### Connector Name

destination-snowflake

### Connector Version

1.2.2

### What step the error happened?

None

### Revelant information

Failure reason: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error: syntax error line 1 at position 54 unexpected 'ORDER'. syntax error line 1 at position 53 unexpected '.'. 

working on airbyte/destination-snowflake:1.1.0, but with the upgrade to airbyte/destination-snowflake:1.2.2 started erroring

### Relevant log output

```shell
destination > ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 Something went wrong in the connector. See the logs for more details. net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 54 unexpected 'ORDER'.
syntax error line 1 at position 53 unexpected '.'.
...
Stack Trace: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 54 unexpected 'ORDER'.
syntax error line 1 at position 53 unexpected '.'.
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by cbuckle1** [comment]
Looks like the same issue as: https://github.com/airbytehq/airbyte/issues/28347 but with Salesforce as the source
