### ISSUE TITLE
[destination-google-sheets] Syncs broken after update to 0.3.0/0.3.1

### ISSUE THREAD

**Issue by asjoholm** [airbytehq/airbyte#56915]
### Connector Name

destination-google-sheets

### Connector Version

0.3.0,0.3.1

### What step the error happened?

During the sync

### Relevant information

All our syncs to google sheets stopped working around March 27th and are still not working. We have tried deleting the destination and setting it up again. We are using oauth and airbyte cloud.

We have around 12 syncs with different models. All failing.

The first error around was `Failure in destination: Config validation error: 'auth_type' is a required property`, then we got the error `'str' object has no attribute 'json'` (0.3.1)

![Image](https://github.com/user-attachments/assets/e5e705cf-0245-4c00-ae01-3088e0d247ee)
![Image](https://github.com/user-attachments/assets/a6269ba1-9bec-4e76-98d2-4a1b5de3a1c4)

Here is an example of the types of a failing job
![Image](https://github.com/user-attachments/assets/d7fffd04-e833-4521-a68e-e94a673b4963)

### Relevant log output

```shell
2025-03-30 17:53:26 platform INFO Connector exited, processing output
2025-03-30 17:53:26 platform INFO ----- START CHECK -----
2025-03-30 17:53:26 platform INFO 
2025-03-30 17:53:26 platform INFO Output file jobOutput.json found
2025-03-30 17:53:26 platform INFO Connector exited with exit code 1
2025-03-30 17:53:26 platform INFO Reading messages from protocol version 0.2.0
2025-03-30 17:53:26 platform ERROR 'str' object has no attribute 'json'
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 12, in <module>
    DestinationGoogleSheets().run(sys.argv[1:])
  File "/usr/local/lib/python3.11/site-packages/airbyte_cdk/destinations/destination.py", line 120, in run
    print(message.json(exclude_unset=True))
          ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'json'
2025-03-30 17:53:26 platform INFO Checking for optional control message...
2025-03-30 17:53:26 platform INFO Writing output of a4cbd2d1-8dbe-4818-b8bc-b90ad782d12a_32101447_4_check to the doc store
2025-03-30 17:53:27 platform INFO Marking workload a4cbd2d1-8dbe-4818-b8bc-b90ad782d12a_32101447_4_check as successful
2025-03-30 17:53:27 platform INFO 
2025-03-30 17:53:27 platform INFO Deliberately exiting process with code 0.
2025-03-30 17:53:27 platform INFO ----- END CHECK -----
2025-03-30 17:53:27 platform INFO
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by asjoholm** [comment]
Migrated to using a service account and it solves the issue.
