### ISSUE TITLE
Octavia CLI command 'octavia get connection' fails

### ISSUE THREAD

**Issue by arimbr** [airbytehq/airbyte#17952]
## Environment
- **Airbyte version**:  0.40.12
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Source Connector and version**: Postgres 1.0.14 
- **Destination Connector and version**: BigQuery 1.2.4 
- **Step where error happened**: octavia get connection "postgres <> bigquery"

## Current Behavior
I manually created a Postgres to BigQuery connection in the Airbyte UI that syncs data correctly.

![Screenshot from 2022-10-13 16-55-14](https://user-images.githubusercontent.com/2302748/195634968-a451f2f9-228b-440f-8ead-425a02edcb96.png)

Then, I run `octavia get connection "postgres <> bigquery"` and it fails:
```
🐙 - Octavia is targetting your Airbyte instance running at http://localhost:8000 on workspace 819c7684-d353-45a1-b2e7-5eb42d8461c0.
Traceback (most recent call last):
  File "/usr/local/bin/octavia", line 8, in <module>
    sys.exit(octavia())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 54, in invoke
    raise e
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 51, in invoke
    result = super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/commands.py", line 97, in connection
    click.echo(get_json_representation(ctx.obj["API_CLIENT"], ctx.obj["WORKSPACE_ID"], Connection, resource))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/commands.py", line 67, in get_json_representation
    return resource.to_json()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/resources.py", line 148, in to_json
    return json.dumps(self.get_remote_resource().to_dict())
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/resources.py", line 140, in get_remote_resource
    return self._find_by_resource_name()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/resources.py", line 108, in _find_by_resource_name
    api_response = self._list_for_workspace_fn(self.api_instance, self.list_for_workspace_payload)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api/web_backend_api.py", line 742, in web_backend_list_connections_for_workspace
    return self.web_backend_list_connections_for_workspace_endpoint.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 849, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 410, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 225, in __call_api
    return_data = self.deserialize(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 326, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1570, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1454, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1374, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 370, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model/web_backend_connection_read_list.py", line 174, in _from_openapi_data
    self.connections = connections
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 185, in __setattr__
    self[attr] = value
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 510, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 157, in set_attribute
    value = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1620, in validate_and_convert_types
    input_value[index] = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1570, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1454, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1374, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 370, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
TypeError: _from_openapi_data() missing 1 required positional argument: 'sync_catalog'
```

## Expected Behavior
I expected the command to return the connection configuration that I set manually on the UI.

The original issue I experienced was when attempting to create a connection with Octavia CLI with `octavia generate connection --source sources/postgres/configuration.yaml --destination destinations/bigquery/configuration.yaml postgres-to-bigquery`. The generated template contained an empty `sync_catalog`.

```
configuration:
  sync_catalog: # OPTIONAL | object | 🚨 ONLY edit streams.config, streams.stream should not be edited as schema cannot be changed.
    streams: []
```

I was expecting the sync_catalog to be filled. Then I created the connection manually through the UI, and tried to get the configuration with the UI with `octavia get connection` and experienced the issue reported above.

## Steps to Reproduce
1. Create a Postgres source with Octavia CLI
2. Create a BigQuery destination with Octavia CLI
3. Apply the changes
4. Manually create a connection in the UI
5. Get the connection details with Octavia CLI

**Comment by arimbr** [comment]
A user in Slack reported that this was working in Airbyte version v0.40.9 and failed from v0.40.10
https://airbytehq-team.slack.com/archives/C02RRUG9CP5/p1666122259855329

**Comment by alexnikitchuk** [comment]
we observe the same issue on Airbyte 0.40.14 during connection import using
`octavia --airbyte-url=http://10.0.117.183:8080/ import connection 0cfb12df-88eb-4bf7-ae05-fb061a113d9f`
```
🐙 - Octavia is targetting your Airbyte instance running at http://10.0.117.183:8080/ on workspace 22994ddd-3501-44a3-a08e-7f48b09326ce.
Traceback (most recent call last):
  File "/usr/local/bin/octavia", line 8, in <module>
    sys.exit(octavia())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 54, in invoke
    raise e
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 51, in invoke
    result = super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/check_context.py", line 91, in wrapper
    f(ctx, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/_import/commands.py", line 156, in connection
    click.echo(import_connection(ctx.obj["API_CLIENT"], ctx.obj["WORKSPACE_ID"], resource))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/_import/commands.py", line 87, in import_connection
    remote_configuration = json.loads(get_json_representation(api_client, workspace_id, UnmanagedConnection, resource_to_get))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/commands.py", line 67, in get_json_representation
    return resource.to_json()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/resources.py", line 148, in to_json
    return json.dumps(self.get_remote_resource().to_dict())
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/resources.py", line 138, in get_remote_resource
    return self._find_by_resource_id()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/get/resources.py", line 129, in _find_by_resource_id
    return self._get_fn(self.api_instance, self.get_payload)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api/web_backend_api.py", line 600, in web_backend_get_connection
    return self.web_backend_get_connection_endpoint.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 849, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 410, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 225, in __call_api
    return_data = self.deserialize(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/api_client.py", line 326, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1570, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1454, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 1374, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 370, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 46, in wrapped_init
    return fn(_self, *args, **kwargs)
TypeError: _from_openapi_data() missing 3 required positional arguments: 'schema_change', 'notify_schema_changes', and 'non_breaking_changes_preference'
```

**Comment by dolphinxyz** [comment]
Hi All, we are experiencing the same issue when running `octavia import all`

**Comment by gv-bdeschutter** [comment]
Same issue here when trying to import a connection on airbyte 0.40.14

**Comment by JonsSpaghetti** [comment]
I wasn't able to reproduce this issue in current version so I'm going to close this issue for now. Can you please try updating your airbyte version to latest? If you run into another problem please create a new issue.
